#
# This file contains configuration flags to customize your site
#

# CUSTOMIZE
# Name of your site (displayed in the header)
# This should be your name or nickname.
name: Your Name

# CUSTOMIZE
# Short bio or description aout you (displayed in the header)
description: CSCI-UA 480 Student, Spring 2023

# CUSTOMIZE
# URL of your avatar or profile pic (the image should be located in the images 
# directory in this repository, or you can change the link to point any image anywhere
# on the web). Replace "weekly" by the name of your own repository.
# It should be "USER_NAME-weekly" in which USER_NAME is replaced by your actual
# user name for GitHub.
avatar: /weekly/images/icon.png 
# fallback text in case image is not served and/or for screen readers
avatar_alt_text: Avatar
# use this separator in your blogs to indicate where the abbreviated part ends and 
# the "Read more ..." link apprears 
excerpt_separator: <!--more-->

# CUSTOMIZE
#
# Flags below are optional - customize them if you wish
# The github flag should be replaced by your own github account name.
#
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: ossd-s23
  instagram:
  linkedin:
  pinterest:
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# CUSTOMIZE
# Your website URL (e.g. https://ossd-s23.github.io/weekly )
# Replace the last part by the name of your own repository.
# It should be "/USER_NAME-weekly" in which USER_NAME is replaced by your actual
# user name for GitHub.

url: "https://ossd-s23.github.io/weekly"

# CUSTOMIZE
# Replace this with the name of your own repository.
# It should be "/USER_NAME-weekly" in which USER_NAME is replaced by your actual
# user name for GitHub.

baseurl: "/weekly"

#
# !! You don't need to change any of the configuration flags below !!
#   (but you may, if you know what you are doing)
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
